
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: valkey
    depends_on:
      migrate:
        condition: service_completed_successfully
      valkey:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O-", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 5s
      start_period: 10s
      retries: 3
    logging: *default-logging

  migrate:
    image: docker.io/migrate/migrate:v4.19.1
    volumes:
      - ./db/migrations:/migrations
    command: >
      -path=/migrations
      -database=postgres://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DATABASE:-postgres}?sslmode=disable
      up
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    logging: *default-logging

  postgres:
    image: docker.io/library/postgres:18.4-alpine3.23
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres} -d ${POSTGRES_DATABASE:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10
    logging: *default-logging

  valkey:
    image: docker.io/valkey/valkey:9.1.0-alpine3.23
    volumes:
      - valkey_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    logging: *default-logging

  cloudflared:
    image: docker.io/cloudflare/cloudflared:2026.2.0
    restart: unless-stopped

    profiles:
      - tunnel
    command: tunnel run --url ${CLOUDFLARE_URL} --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      app:
        condition: service_started
    logging: *default-logging
volumes:
  postgres_data:
  valkey_data:
