services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    restart: unless-stopped
    environment:
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      migrate:
        condition: service_completed_successfully
      redis:
        condition: service_healthy

  migrate:
    image: docker.io/migrate/migrate:v4.19.1
    volumes:
      - ./db/migrations:/migrations
    command: >
      -path=/migrations
      -database=postgres://${POSTGRES_USERNAME:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DATABASE:-postgres}?sslmode=disable
      up
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure

  postgres:
    image: docker.io/library/postgres:18.4-alpine3.23
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME:-postgres} -d ${POSTGRES_DATABASE:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: docker.io/library/redis:8.6.3-alpine3.23
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  redis_data:
